### ISSUE TITLE
syntax highlighting does not work as expected

### ISSUE THREAD

**Issue by haim-ari** [halogenica/beautifulhugo#260]
Trying to have full support with correct syntax highlighting.
as you can see at the screenshot it does not seem to work correctly.

Hugo version: 0.54.0
config.toml:

```
DefaultContentLanguage = "en"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = false

[Params]
  useHLJS = true
```

on the post page (md) i use the " \`\`\`yaml " fences:

![Screenshot from 2019-04-02 20-59-43](https://user-images.githubusercontent.com/4179195/55425142-659ac380-558a-11e9-8aba-69151c8688d0.png)

**and instead of looking like this:**

```yaml

image: docker:git
services:
  - docker:dind

stages:
  - build
  - deploy
  - test
  - rollback

variables:
  IMAGE_TAG: $CI_PROJECT_NAME:$CI_COMMIT_SHA
  IMAGE_NAME: $ECR_REPO/$IMAGE_TAG;

build:
  stage: build
  script:
    # Setup
    - export AWS_REGION=&quot;us-east-1&quot;
    - export AWS_ACCESS_KEY_ID=$aws_access_key_id
    - export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
    - export REPO=$ECR_REPO
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    # AUTH
    - CERT=`aws ecr get-login --no-include-email --region ${AWS_REGION}`
    - ${CERT}
    # Build
    - docker build -t ${CI_PROJECT_NAME} .
    - docker tag $CI_PROJECT_NAME:latest $REPO/$IMAGE_TAG
    - docker tag $CI_PROJECT_NAME:latest $REPO/${CI_PROJECT_NAME}:latest
    - docker push $REPO/$IMAGE_TAG
    - docker push $REPO/${CI_PROJECT_NAME}:latest
  environment:
    name: staging
```

**It looks like this:** (screenshot) 

![Screenshot from 2019-04-02 20-36-20](https://user-images.githubusercontent.com/4179195/55423798-58c8a080-5587-11e9-9241-cc89ef5c183b.png)

What am i missing ?
Thank you
