### ISSUE TITLE
Missing "blog-post" class?

### ISSUE THREAD

**Issue by v1bri** [halogenica/beautifulhugo#290]
The `blog-post` class is referenced in [`single.html`](https://github.com/halogenica/beautifulhugo`/blob/master/layouts/_default/single.html#L5) but is not defined in any style sheet. Is this an intentional omission or an accident?

I discovered this while investigating why post previews display in Open Sans on the main page while actual posts display in Times New Roman. The following is a quick fix.

```css
.blog-post {
  font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```
