### ISSUE TITLE
How to add an "About" section in a multilingual setup?

### ISSUE THREAD

**Issue by juacq97** [halogenica/beautifulhugo#344]
Hi! I have a little multilingual blog, I want to create an "about" menu, one in english and one on spanish. I added this:

```toml
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Acerca"
        url = "/es/page/acerca"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        url = "en/page/about"
```

and then created `content/es/page/acerca.org` and  `content/es/page/about.org` but when I try the server and click on the about link I get "error 404". How I can add menus (about section)? thanks!

**Comment by whatacold** [comment]
Hi,

I think this should work, i.e. without the language prefix, thought I haven't test it myself:
```toml
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Acerca"
        url = "page/acerca"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        url = "page/about"
```

I have a similar setup at https://whatacold.io/, hope this helps!
