### ISSUE TITLE
How to configure social media links?

### ISSUE THREAD

**Issue by zachriggle** [halogenica/beautifulhugo#384]
I noticed that there appears to be some support for social media links (either for sharing or to link to our account, it's not clear) as shown by the items in `themes/beautifulhugo/data/beautifulhugo/social.toml`.

How do I configure the social icons from my `config.yaml`?  It seems that something like this should work, but I haven't figured out the exact way of setting these values so they show up in the footer.

```yaml
params:
  social_icons:
    github: Gallopsled/pwntools
```

**Comment by zachriggle** [comment]
Figured it out, it goes under the top-level `author` field, e.g.

```yaml
author: 
  name: "Team Gallopsled"
  website: "https://github.com/Gallopsled"
  github: Gallopsled/pwntools
  twitter: Pwntools
```
