### ISSUE TITLE
Odd code syntax highlighting when using `useHLJS = true` and Chroma

### ISSUE THREAD

**Issue by robamu** [halogenica/beautifulhugo#418]
Hello,

Hugo version: hugo v0.91.2+extended linux/amd64 BuildDate=2021-12-23T20:50:11Z
OS: Ubuntu 21.04

Pygments and Python3 are installed.

I have issue with problematic syntax highlighting right now.
My `config.toml` looks like this:

```toml
baseURL = "https://robamu.github.io"
languageCode = 'en-us'
title = 'robs blog'
theme = "beautifulhugo"
disqusShortname = "https-robamu-github-io"

pygmentsStyle = "pygments"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  title = "robs blog"
  keyword = "coding, rust, c++, python, aerospace, satellites"
  about_me = true
  commit = false
  comments = true
  useHLJS = false
  # useHLJS = true
  readingTime = true
  socialShare = true
  showRelatedPosts = true
  delayDisqus = true
  # Google Programmable Search Engine
  gcse = "49f27010d1fda4554"
  # Footer section
  [params.footer]
    enable = true

...
```

If I use `useHLJS = false`, the rust code block seems to be rendered fine

![rust-code-block](https://user-images.githubusercontent.com/31589589/147479196-11b1b616-684e-4a2d-8ef7-fb4d2f0a12be.png)

However, the console markup on another page is problematic now. There is no slidebar, and some stuff is cut-off:

![console-markup](https://user-images.githubusercontent.com/31589589/147479276-049aef35-8d35-40ee-8128-7bfee1e1b5a5.png)

If I use `useHLJS = true`, the rendering for the Rust code doesnt seem to work anymore:

![bland](https://user-images.githubusercontent.com/31589589/147479376-16de2b0a-dcdb-483c-bed0-fef1831d196c.png)

but now the `console` snippet looks like I want it to be

![console-snippet](https://user-images.githubusercontent.com/31589589/147479485-5abbfdb1-1cf0-4693-8c78-16d854e4ee18.png)

slidebar is there and the colors look better as well.

Do you have any ideas what might be the issue?
How to best debug this?
