### ISSUE TITLE
add config flag to control bigimg stretching

### ISSUE THREAD

**Issue by gnalck** [halogenica/beautifulhugo#42]
First of all, great work, this is the best hugo theme I have seen so far, thank you for migrating it from the Jekyll counterpart.

For the images on a site I'm creating, I would like them to not stretch at all. Perhaps the extra space on either side of the image can just be some sort of grey-fill? This is useful if the image has details at the top or bottom one does not want omitted, for example.

**Comment by liwenyip** [comment]
To solve your issue, open main.css and change `cover;` to `contain;` on lines 429-432 and 442-445 (8 instances total).

If you want grey-fill at the sides, insert the following line into `.intro-header.big-img` and `.intro-header.big-img  .big-img-transition`:
```
background-color: lightgrey;
```

I'm not sure it's worth building a flag for this into the template, but let's let @halogenica decide.

**Comment by halogenica** [comment]
I'm glad it's working out for you @gnalck! As for changing the bigimg behavior, @liwenyip kindly provided a solution for you. Generally I think you should feel free to make these nuanced customizations in your own local version. However, I would also gladly accept a pull request if you do decide to make the customizations user-friendly. For example, if the default bigimg behavior stayed the same, but a "bigimgstyle" field was added to the config.toml that could define the behavior like "fill", "fit", "center", "span", etc, that could be a nice customization for other people. 

If you'd like to see it in the theme (so you don't have to maintain your own customizations), please make a pull request and I'll be happy to review it and add it.

**Comment by liwenyip** [comment]
Maybe what ___is___ worth adding is a param in `config.toml` and/or front matter that lets you load a custom css file e.g. `/static/css/custom.css`.

Then @gnalck could avoid having to maintain his own customisations by putting this in a custom css file:

```css
.intro-header.big-img, .intro-header.big-img  .big-img-transition {
  -webkit-background-size: contain !important;
  -moz-background-size: contain !important;
  background-size: contain !important;
  -o-background-size: contain !important;
  background-color: lightgrey;
}
```

I'll add this to my to do list :-)
